// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7IwVqn3EWPtPH8wDawINgEOMFXNl-2eA',
    appId: '1:359727259191:web:89c31cea114ed4421529b2',
    messagingSenderId: '359727259191',
    projectId: 'push-notification-53d36',
    authDomain: 'push-notification-53d36.firebaseapp.com',
    storageBucket: 'push-notification-53d36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiPEXPTlj7xMawTfibfyjU7diqsBYBAzE',
    appId: '1:359727259191:android:997ddfb9ff582d431529b2',
    messagingSenderId: '359727259191',
    projectId: 'push-notification-53d36',
    storageBucket: 'push-notification-53d36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX9ibfrzmbIEig9fkgXuziWsFpWvPHRYo',
    appId: '1:359727259191:ios:d3cdbbeb5690724d1529b2',
    messagingSenderId: '359727259191',
    projectId: 'push-notification-53d36',
    storageBucket: 'push-notification-53d36.appspot.com',
    iosBundleId: 'com.example.pushtrial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7IwVqn3EWPtPH8wDawINgEOMFXNl-2eA',
    appId: '1:359727259191:web:8dc2515c7258132d1529b2',
    messagingSenderId: '359727259191',
    projectId: 'push-notification-53d36',
    authDomain: 'push-notification-53d36.firebaseapp.com',
    storageBucket: 'push-notification-53d36.appspot.com',
  );
}
